/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagment;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author elate
 */
public class RegAdmin extends javax.swing.JFrame {

    /**
     * Creates new form RegAdmin
     */
    sqlDriverConn con=new sqlDriverConn();
    Connection connect=con.EstablishCon();
    public RegAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        long millis=System.currentTimeMillis();  
        java.sql.Date date=new java.sql.Date(millis); 
        dob.setDate(date);
        
        
       
    }
    
    
    
    
    public void Close(){
             WindowEvent WCE=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
             Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(WCE);
             
         }
     private boolean isAnyRequiredFieldEmpty() {
        return fname.getText().equals("") || lname.getText().equals("") || address.getText().equals("")||email.getText().equals("")||phone.getText().equals("")||adminname.getText().equals("")||passcode.getText().equals("");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        passcode = new javax.swing.JTextField();
        adminname = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        dob = new com.toedter.calendar.JDateChooser();
        gender = new javax.swing.JComboBox<>();
        empposition = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(251, 246, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204))));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figures/admin.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setText("Admin Registration");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setText("Last Name : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setText("PassCode :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel8.setText("DOB :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 70, 20));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel9.setText("Gender :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel10.setText("Address : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setText("First Name :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 90, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel12.setText("Admin Name :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        fname.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnameFocusLost(evt);
            }
        });
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 150, 30));

        lname.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 150, 30));

        address.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 150, 30));

        passcode.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        passcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(passcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 150, 30));

        adminname.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        adminname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(adminname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 150, 30));

        submit.setBackground(java.awt.SystemColor.activeCaption);
        submit.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 150, 30));

        cancel.setBackground(java.awt.SystemColor.inactiveCaption);
        cancel.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figures/CANCEL.PNG"))); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 150, 30));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel13.setText("Phone # ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        phone.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("Emp Position :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel14.setText("Email :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        email.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 150, 30));
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 150, 30));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Intersex" }));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 150, 30));

        empposition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sales Manager", "Product Manager", "Finance Manager", "Human Resources", "Sales Representative", " " }));
        jPanel1.add(empposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
    Close();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed
     
    public boolean checkRepeatAdminName(String name){
        boolean confirm=false;
        PreparedStatement statement;     
        try {
                String st="select AdminName from AdminAccount";
                statement = connect.prepareStatement(st);
                ResultSet resultSet = statement.executeQuery();
                
                while(resultSet.next()){
                    String dbname=resultSet.getString(1);
               
                    
                    if(name.equals(dbname)){
                   
                        confirm=true;
                    }
            }
                
              
        
        } catch (SQLException ex) {
            Logger.getLogger(RegAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return confirm;
    }     
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        SimpleDateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
            String date=df1.format(dob.getDate());
//            System.out.println(date);
            
            String fname=this.fname.getText();
            String lname=this.lname.getText();
            String position=(String) empposition.getSelectedItem();
            String gender=(String) this.gender.getSelectedItem();
            String address=this.address.getText();
            String email=this.email.getText();
            String phone=this.phone.getText();
            String adminName=this.adminname.getText();
            String adminPass=this.passcode.getText();
            
            
        if(isAnyRequiredFieldEmpty()!=false){
               JOptionPane.showMessageDialog(this,"All fields are Required.");
           }
           else{
                
            if(checkRepeatAdminName(adminName)==true){
                
                JOptionPane.showMessageDialog(this,"Admin name is already registered\nUse diffrent one..","Admin Name",JOptionPane.ERROR_MESSAGE);
            }
            else{
                boolean signin=false;
                int adminid=0;
               try {
                     Statement st = connect.createStatement();
                     st.executeUpdate("insert into adminAccount(AdminName,AdminPassword) values('"+adminName+"','"+adminPass+"')");
                        
                        
                            PreparedStatement statement;
                        String stmt="select Adminid from AdminAccount where AdminName='"+adminName+"'";
                        statement = connect.prepareStatement(stmt);
                        ResultSet resultSet = statement.executeQuery();
                        
                        while(resultSet.next()){
                            adminid=resultSet.getInt(1);
                            
                        }
                        
                        st.executeUpdate("insert into adminDetail(fname,lname,position,DOB,gender,empAddress,phoneno,email,adminid) values('"+fname+"','"+lname+"','"+position+"','"+date+"','"+gender+"','"+address+"','"+phone+"','"+email+"','"+adminid+"')"); 
                     
                        signin=true;
               
               } catch (SQLException ex) {
                         
                     Logger.getLogger(RegAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
            if(signin==true){
                
                        ImageIcon icon = new ImageIcon("src/Figures/MODIFY.png");
                JOptionPane.showMessageDialog(this, "Hi "+fname+"\n\tAdmin ID : "+adminid+"\n\tAdmin Name : "+adminName+"\n\tPasscode : "+adminPass+"","Remember this",JOptionPane.INFORMATION_MESSAGE,icon);
                Close();
            
            }
            }
            
           }
           
    }//GEN-LAST:event_submitActionPerformed

    private void fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusLost
               String fname=this.fname.getText().toLowerCase();
        	Random objGenerator = new Random();
            
              int randomNumber = objGenerator.nextInt(1000);
              String generatedname=fname+randomNumber;
              if(fname.equals("")){
                }
              else{
                 adminname.setText(generatedname);

              }
              
     
    }//GEN-LAST:event_fnameFocusLost

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
    }//GEN-LAST:event_emailFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
            if(email.getText().equals("")){
                email.setText(email.getText()+"@gmail.com"); 
                email.select(0, 0);
            }
// TODO add your handling code here:
    }//GEN-LAST:event_emailFocusGained

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField adminname;
    private javax.swing.JButton cancel;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> empposition;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField passcode;
    private javax.swing.JTextField phone;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
